# Change these first
owner: KUNI-Global # Your GitHub organization or username, where this repository lives
repo: radar # The name of this repository

assignees: 
  - kuninyao

sites:
  - name: KUNI — main HTTPS
    url: https://ku.ni
  - name: KUNI — main HTTP
    url: http://ku.ni
  - name: KUNI — FastDL HTTPS
    url: https://fastdl.ku.ni
  - name: KUNI — FastDL HTTP
    url: http://fastdl.ku.ni
  - name: KUNI — Cloudflare Check IPv4
    url: ku.ni
    port: 443
    check: "tcp-ping"
    ipv6: true
  - name: KUNI — Cloudflare Check IPv4
    url: ku.ni
    port: 443
    check: "tcp-ping"
    ipv6: false

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.ku.ni
  # baseUrl: /your-repo-name
  logoUrl: https://logos.ku.ni/3_0.svg
  baseUrl: /
  name: KUNI Status
  introTitle: KUNI Status
  introMessage: Powered by [upptime](https://github.com/upptime/upptime). 
  navbar:
    - title: Status
      href: /

commitMessages:
  commitAuthorName: "kuninyao"
  commitAuthorEmail: "i@ku.ni"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
